import { lazy, Suspense, useState } from "react";
import { Link } from "react-router-dom";
import { games } from "@/games/registry";
import { PlayIcon, TrophyIcon } from "@/components/Icons";
import character from "@/assets/character.webp";
import "./Home.css";

const LeaderboardModal = lazy(() =>
  import("@/components/LeaderboardModal").then((m) => ({
    default: m.LeaderboardModal,
  })),
);

// Every game folder ships a banner.webp (generated by scripts/make_banners.sh);
// key the eager glob by the folder name so it lines up with the game id.
const banners = Object.fromEntries(
  Object.entries(
    import.meta.glob<string>("@/games/*/banner.webp", {
      eager: true,
      import: "default",
    }),
  ).map(([path, url]) => [path.split("/").at(-2), url]),
);

export function Home() {
  const [openGameId, setOpenGameId] = useState<string | null>(null);
  const openGame = games.find((g) => g.id === openGameId);

  return (
    <div className="home">
      <h1>
        Retr
        <img src={character} alt="o" className="home-title-o" /> Arcade
      </h1>
      <p>Welcome to the Retro Arcade!</p>
      <ul className="game-grid">
        {games.map((game) => (
          <li key={game.id} className="game-card">
            <div className="game-card-header">
              <img
                src={
                  banners[game.id] ??
                  `${import.meta.env.BASE_URL}images/game-placeholder.svg`
                }
                alt=""
                className="game-card-image"
              />
              <div className="game-card-info">
                <h2 className="game-card-title">{game.title}</h2>
                <p className="game-card-description">{game.description}</p>
              </div>
            </div>

            <div className="game-card-actions">
              <Link
                to={`/games/${game.id}`}
                className="game-card-btn game-card-btn-play"
              >
                <PlayIcon />
                Play
              </Link>
              <button
                type="button"
                className="game-card-btn game-card-btn-leaderboard"
                onClick={() => setOpenGameId(game.id)}
              >
                <TrophyIcon />
                Leaderboard
              </button>
            </div>
          </li>
        ))}
      </ul>
      {openGame && (
        <Suspense fallback={null}>
          <LeaderboardModal
            gameId={openGame.id}
            title={openGame.title}
            onClose={() => setOpenGameId(null)}
          />
        </Suspense>
      )}
    </div>
  );
}
